// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact       = require("reason-react/src/ReasonReact.js");
var ReactMotion       = require("react-motion");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(defaultStyle, style, children) {
  return ReasonReact.wrapJsForReason(ReactMotion.Motion, {
              style: style,
              defaultStyle: Js_null_undefined.from_opt(defaultStyle)
            }, children);
}

var Motion = /* module */[/* make */make];

function make$1(defaultStyles, willEnter, willLeave, styles, children) {
  return ReasonReact.wrapJsForReason(ReactMotion.TransitionMotion, {
              styles: styles,
              defaultStyles: Js_null_undefined.from_opt(defaultStyles),
              willEnter: Js_null_undefined.from_opt(willEnter),
              willLeave: Js_null_undefined.from_opt(willLeave)
            }, children);
}

var TransitionMotion = /* module */[/* make */make$1];

var New = /* module */[
  /* Motion */Motion,
  /* TransitionMotion */TransitionMotion
];

exports.New = New;
/* ReasonReact Not a pure module */
