// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var React$1 = require("@storybook/react");
var Slider$ReasonSlider = require("../src/Slider.js");
var AddonKnobs = require("@storybook/addon-knobs");

var _module = module;

function getPointer(item, param) {
  return item[/* id */1];
}

function getItem(p, items) {
  return List.find((function (item) {
                return item[/* id */1] === p;
              }), items);
}

var GallerySlide = /* module */[
  /* getPointer */getPointer,
  /* getItem */getItem
];

var GallerySlider = Slider$ReasonSlider.Make([
      getItem,
      getPointer
    ]);

React$1.storiesOf("Slider", _module).addDecorator(AddonKnobs.withKnobs).add("test", (function (param) {
        return ReasonReact.element(undefined, undefined, Curry.app(GallerySlider[/* Component */1][/* make */23], [
                        /* :: */[
                          /* record */[
                            /* src */"https://dummyimage.com/100x100/1abc9c/fff",
                            /* id */"safora",
                            /* height */100,
                            /* width */100
                          ],
                          /* :: */[
                            /* record */[
                              /* src */"https://dummyimage.com/500x500/1abc9c/fff",
                              /* id */"brasil",
                              /* height */500,
                              /* width */500
                            ],
                            /* :: */[
                              /* record */[
                                /* src */"https://dummyimage.com/1000x1000/1abc9c/fff",
                                /* id */"soller",
                                /* height */1000,
                                /* width */1000
                              ],
                              /* :: */[
                                /* record */[
                                  /* src */"https://dummyimage.com/2000x2000/1abc9c/fff",
                                  /* id */"lisboa",
                                  /* height */2000,
                                  /* width */2000
                                ],
                                /* :: */[
                                  /* record */[
                                    /* src */"https://dummyimage.com/5000x1000/1abc9c/fff",
                                    /* id */"lisboa3",
                                    /* height */1000,
                                    /* width */5000
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* src */"https://dummyimage.com/1000x5000/1abc9c/fff",
                                      /* id */"lisboa2",
                                      /* height */5000,
                                      /* width */1000
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* src */"https://dummyimage.com/3000x3000/1abc9c/fff",
                                        /* id */"lisboa4",
                                        /* height */3000,
                                        /* width */3000
                                      ],
                                      /* :: */[
                                        /* record */[
                                          /* src */"https://dummyimage.com/2000x1800/1abc9c/fff",
                                          /* id */"lisboa5",
                                          /* height */1800,
                                          /* width */2000
                                        ],
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ],
                        (function (param) {
                            var item = param[/* item */1];
                            var target = document.getElementById("slider-content");
                            var match = Curry._2(GallerySlider[/* Calculations */0][/* calculateFullscreenImageDimensions */4], /* tuple */[
                                  item[/* width */3],
                                  item[/* height */2]
                                ], (target == null) ? undefined : Caml_option.some(target));
                            return React.createElement("div", {
                                        style: {
                                          display: "flex",
                                          height: "100%",
                                          position: "absolute",
                                          width: "100%",
                                          flexDirection: "column"
                                        }
                                      }, React.createElement("div", {
                                            style: {
                                              height: "100px"
                                            }
                                          }, item[/* id */1]), React.createElement("div", {
                                            id: "slider-content",
                                            style: {
                                              display: "flex",
                                              position: "relative",
                                              alignItems: "center",
                                              flexDirection: "column",
                                              flexGrow: "1",
                                              justifyContent: "center"
                                            }
                                          }, React.createElement("div", undefined, React.createElement("img", {
                                                    style: {
                                                      height: String(match[1]) + "px",
                                                      verticalAlign: "bottom",
                                                      width: String(match[0]) + "px"
                                                    },
                                                    src: item[/* src */0]
                                                  }))), React.createElement("div", {
                                            style: {
                                              height: "25px"
                                            }
                                          }));
                          }),
                        (function (c) {
                            console.log("change", c);
                            return /* () */0;
                          }),
                        (function (param) {
                            var show = param[/* show */0];
                            return React.createElement("img", {
                                        src: "https://dummyimage.com/200x200/1abc9c/fff",
                                        onClick: (function (e) {
                                            return Curry._1(show, "lisboa");
                                          })
                                      });
                          }),
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        /* array */[]
                      ]));
      }));

exports._module = _module;
exports.GallerySlide = GallerySlide;
exports.GallerySlider = GallerySlider;
/* _module Not a pure module */
