// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


var Knobs = /* module */[];

var Addons = /* module */[/* Knobs */Knobs];

exports.Addons = Addons;
/* No side effect */
